[package]
name = "game"
version = "0.1.0"
authors = ["Bjørnar Luteberget <luteberget@gmail.com>"]
edition = "2018"

[dependencies]
model = { path = "../model" }
ws = "*"
webbrowser = "*"
serde_json = "*"
structopt = "*"
shell-words="0.1"
